name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Test
        run: ./gradlew --info test

  publish-snapshot:
    needs: test
    runs-on: ubuntu-20.04
    environment:
      name: snapshots
      url: https://oss.sonatype.org/content/repositories/snapshots/lv/ctco/scm/gradle-mobile-plugin/
    env:
      ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
      ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_PASSWORD}}
      ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSWORD}}
      SIGNING_KEY: ${{secrets.SIGNING_KEY}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Publish snapshot
        run: |
          ./gradlew --info :setupSigningKey
          ./gradlew --info assemble uploadArchives
