name: Release

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Test
        run: ./gradlew --info test

  perform-release:
    needs: test
    runs-on: ubuntu-20.04
    environment:
      name: releases
      url: https://repo1.maven.org/maven2/lv/ctco/scm/gradle-mobile-plugin/
    env:
      ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
      ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_PASSWORD}}
      ORG_GRADLE_PROJECT_signingPassword: ${{secrets.SIGNING_PASSWORD}}
      SIGNING_KEY: ${{secrets.SIGNING_KEY}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Perform release
        run: |
          git config --global user.email "cscm@ctco.lv"
          git config --global user.name "CSCM"
          git remote set-url origin https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          ./gradlew --info :setupSigningKey
          ./gradlew --info release closeAndReleaseRepository -Prelease.useAutomaticVersion=true
